;;; init.el --- Emacs main configuration file -*- lexical-binding: t; buffer-read-only: t; no-byte-compile: t -*-

;; Author: Nicolas CHAPON
;; Keywords: Emacs configuration
;; Homepage:

;;; Commentary:
;; Emacs config file.
;; This file was automatically generated by `org-babel-tangle'.
;; Do not change this file.  Main config is located in Readme.org at `user-emacs-directory'

;;; Code:

(unless (featurep 'early-init)
  (load (expand-file-name "early-init" user-emacs-directory)))

(straight-use-package 'use-package)
(defvar straight-use-package-by-default)
(setq straight-use-package-by-default t)
(require 'use-package)

(use-package diminish)

(use-package exec-path-from-shell
  :config
  (when (memq window-system '(mac ns x))
    (progn
      (exec-path-from-shell-initialize)
      ;; (exec-path-from-shell-copy-env "GOPATH")
      ;;(exec-path-from-shell-copy-env "JAVA_HOME")
      ;; (exec-path-from-shell-copy-env "PATH")
      (exec-path-from-shell-copy-env "XDG_CONFIG_HOME")
      )))

(use-package no-littering)

(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

(require 'setup-prefs)
(require 'setup-ui)
(require 'setup-keys)
(require 'setup-windows)
(require 'setup-core)
(require 'setup-completion)
(require 'setup-org)
(require 'setup-programming)
(require 'setup-shell)
(require 'setup-functions)

(provide 'init)
;;; init.el ends here
