;;; setup-keys.el --- Key Bindings module -*- lexical-binding: t; buffer-read-only: t; no-byte-compile: t -*-

;; Author: Nicolas CHAPON
;; Keywords: Emacs configuration
;; Homepage:

;;; Commentary:
;; Emacs config file.
;; This file was automatically generated by `org-babel-tangle'.
;; Do not change this file.  Main config is located in Readme.org at `user-emacs-directory'

;;; Code:

;; Unbind unneeded keys
(global-set-key (kbd "C-z") nil)
(global-set-key (kbd "C-l") nil)
(global-set-key (kbd "M-z") nil)
(global-set-key (kbd "C-x C-z") nil)
(global-set-key (kbd "M-o") nil)
(global-set-key (kbd "M-SPC") nil)


(global-set-key (kbd "C-+") #'text-scale-increase)
(global-set-key (kbd "C--") #'text-scale-decrease)

;; Prefer backward-kill-word over Backspace
(global-set-key (kbd "C-w") #'backward-kill-word)
(global-set-key (kbd "C-x C-k") #'kill-region)

(global-set-key (kbd "C-x C-r") #'recentf-open-files)

;; Move up/down paragraph
(global-set-key (kbd "M-n") #'forward-paragraph)
(global-set-key (kbd "M-p") #'backward-paragraph)
(global-set-key (kbd "C-x c") #'compile)

;; Remap goto-map 
(global-set-key (kbd "C-M-g") goto-map)

;; Functions
(bind-keys
 ("<f5>" . revert-buffer)
 ("C-<f5>" . magit-log-buffer-file)
 ("<f9>" . treemacs)
 ("<f11>" . nc/maximize-or-split-window-vertically)
 ("C-<f11>" . nc/split-window-horizontally)
 ("<f12>" . org-agenda)
 ("C-<f12>" . org-agenda))

;; Tools alt-[0-9]
(bind-keys
 ("M-0" . nc/maximize-or-split-window-vertically))

(use-package key-chord
  :init
  (key-chord-mode 1)
  (key-chord-define-global "FF" 'projectile-find-file)
  (key-chord-define-global "::" 'avy-goto-char-timer)
  (key-chord-define-global "GG" 'consult-ripgrep)  
  (key-chord-define-global "OO" 'consult-outline)
  (key-chord-define-global "DD" 'delete-region)
  (key-chord-define-global "??" 'nc/search-notes) 
  (key-chord-define-global "BB" 'beginning-of-buffer)
  (key-chord-define-global "JJ" 'crux-top-join-line)
  (key-chord-define-global "MM" 'nc/maximize-or-split-window-vertically)
  (key-chord-define-global "$$" 'end-of-buffer))

(use-package which-key
  :diminish
  :custom
  (which-key-separator " ")
  (which-key-prefix-prefix "+")
  :config
  (which-key-mode)
  (which-key-enable-god-mode-support))

;; Eanble transinet menus
(use-package transient
    :commands (transient-define-prefix))



;; Stolen from Doom
(defun nc/yank-buffer-path ()
  "Copy the file name or directory name of the current buffer to the clipboard."
  (interactive)
  (let* ((filename (or buffer-file-name default-directory))
         (project (ignore-errors (project-root (project-current))))
         (relpath (if (and project (file-in-directory-p filename project))
                      (file-relative-name filename project)
                    nil)))
    (kill-new
     (cond
      ((equal current-prefix-arg '(4)) ; C-u
       (file-name-nondirectory filename))
      ((equal current-prefix-arg '(16)) ; C-u C-u
       (or relpath filename))
      (t
       filename)))
    (message "Copied: %s"
             (substring-no-properties (car kill-ring)))))



(transient-define-prefix nc/yank-path-submenu ()
  "Yank Paths"
  
  [["Yank Paths"
   ("F" "Full path"
    (lambda () (interactive)
      (let ((current-prefix-arg nil))
        (call-interactively #'nc/yank-buffer-path))))

   ("y" "Filename only  (C-u)"
    (lambda () (interactive)
      (let ((current-prefix-arg '(4)))
        (call-interactively #'nc/yank-buffer-path))))

   ("Y" "Yank project-relative path  (C-u C-u)"
    (lambda () (interactive)
      (let ((current-prefix-arg '(16)))
        (call-interactively #'nc/yank-buffer-path))))
   ]])

(defun nc/goto-ssh-config-file ()
  "Goto my ssh config files"
  (interactive)
  (find-file "~/.ssh/config"))

(defun nc/goto-authinfo-file ()
  "Goto my auth info file"
  (interactive)
  (find-file "~/.authinfo.gpg"))


(transient-define-prefix nc/file-menu ()
  "File"
  
  [["Actions"
   ("r" "Rename file & buffer" rename-visited-file)
   ("d" "Delete file & buffer" crux-delete-file-and-buffer)
   ("c" "Copy file" crux-copy-file-preserve-attributes)
   ("y" "Yank buffer path..." nc/yank-path-submenu)]
  ])


(transient-define-prefix nc/goto-menu ()
  "Goto Transient Menu"
  
  [["Config File & Credentials"
    ("e" "Emacs Config" nc/goto-emacs-config)
    ("p" "Credentials" nc/goto-my-credentials)
    ("s" "SSH config"  nc/goto-ssh-config-file)
    ("a" "Authinfo"  nc/goto-authinfo-file)
  ]
  ["Dirs"
    ("A" "Archives" nc/goto-archives-dir)
    ("H" "Home" (lambda () (interactive) (dired "~")))
    ("N" "Notes" nc/goto-notes-dir)
    ("T" "Templates" nc/goto-templates-dir)
    ("P" "Projects" nc/goto-projects-dir)
    ]])


(transient-define-prefix nc/search-menu ()
  "Transient Search Menu"
  ["Search"
   ["Org Files"
    ("a" "Agenda Heading" consult-org-agenda)
    ("n" "Notes" nc/search-notes)]
   ["Projects"
    ("p" "Search in Projects" nc/consult-rg-my-projects)
    ("." "symbol" nc/consult-line-symbol-at-point)]])

(transient-define-prefix nc/window-menu ()
  "Simple frame, window and buffer management."
  ["Frame, Window & Buffer Manager"
   
   ["Frames"
    ("n" "New frame" make-frame-command)
    ("d" "Delete frame" delete-frame)
    ("o" "Other frame" other-frame)
    ("D" "Only this frame" delete-other-frames)
    ("m" "Maximize" toggle-frame-maximized)
    ("f" "Fullscreen" toggle-frame-fullscreen)]
   
   ["Layouts"
    ("L i" "IDE layout" nc/layout-ide)
    ("L l" "Sidebar left" nc/layout-sidebar-left)
    ("L r" "Sidebar right" nc/layout-sidebar-right)]
   
   ["Buffers"
    ("B" "Buffer other window" switch-to-buffer-other-window)
    ("F" "Buffer other frame" switch-to-buffer-other-frame)
    ("b" "Display buffer" display-buffer)
    ("K" "Kill buffer & window" kill-buffer-and-window)
    ("i" "Ibuffer" ibuffer)]
   
   ["Actions"
    ("s" "Save config" window-configuration-to-register)
    ("r" "Restore config" jump-to-register)
    ("x" "Swap windows" window-swap-states)
    ("q" "Quit" transient-quit-one)]])


(defvar-keymap nc-code-map
  :doc "My custom coding (LSP) map"
  ;; Code
  "s" #'consult-lsp-symbols
  "r" #'lsp-rename
  "o" #'lsp-organize-imports
  "X" #'lsp-treemacs-errors-list
  ":" #'lsp-treemacs-call-hierarchy
  "S" #'lsp-treemacs-symbols
  "?" #'lsp-treemacs-references)

(keymap-set global-map "C-c l" nc-code-map)

(defvar-keymap nc-file-map
  :doc "My custom file keymap"
  ;; File Commands
  "." #'ffap
  "M-." #'ffap-menu
  "c" #'crux-copy-file-preserve-attributes
  "d" #'crux-delete-file-and-buffer
  "r" #'rename-visited-file
  "y" #'nc/yank-buffer-path
  "m" #'nc/file-menu)

(keymap-set global-map "C-c f" nc-file-map)

(defvar-keymap nc-goto-map
  :doc "My custom goto keymap"
  "e" #'nc/goto-emacs-config
  "a" #'nc/goto-authinfo-file
  "p" #'nc/goto-my-credentials
  "s" #'nc/goto-ssh-config-file
  "A" #'nc/goto-archives-dir
  "P" #'nc/goto-projects-dir
  "N" #'nc/goto-notes-dir
  "T" #'nc/goto-templates-dir)

(keymap-set global-map "C-c g" nc-goto-map)

(defvar-keymap nc-insert-map
  :doc "My custom insert map"
  ;; Insert
  "d" #'nc/insert-datestamp-inactive
  "D" #'nc/insert-datestamp
  "e" #'emoji-search
  "p" #'nc/generate-password
  "q" #'quoted-insert
  "t" #'tempel-insert
  "u" #'nc/uuid
  "y" #'consult-yasnippet
  "Y" #'yankpad-insert)

(keymap-set global-map "C-c i" nc-insert-map)

(defvar-keymap nc-kill-map
  :doc "My custom kill map"
  "f" #'delete-frame
  "b" #'kill-buffer-and-window)

(keymap-set global-map "C-c k" nc-kill-map)

(defvar-keymap nc-notes-map
  :doc "My custom notes map"
  ;; Notes
  "a" #'consult-org-agenda
  "c" #'org-clock-goto
  "d" #'denote-dired
  "l" #'org-store-link
  "s" #'nc/search-notes
  "t" #'org-todo-list
  "v" #'org-search-view)

(keymap-set global-map "C-c n" nc-notes-map)

(defvar-keymap nc-project-map
  :doc "My custom kill map"
  "," #'projectile-edit-dir-locals
  "c" #'consult-projectile
  "f" #'nc/consult-fd-my-projects
  "p" #'projectile-command-map
  "s" #'nc/consult-rg-my-projects)

(keymap-set global-map "C-c p" nc-project-map)

(defvar-keymap nc-search-map
  :doc "My custom kill map"
  "." #'nc/consult-line-symbol-at-point)

(keymap-set global-map "C-c s" nc-search-map)

(defvar-keymap nc-version-map
  :doc "My custom Version Control Map"
  "f" #'nc/vc-browse-remote-current-line
  "R" #'nc/vc-browse-remote)

(keymap-set global-map "C-c v" nc-version-map)

(defvar-keymap nc-window-map
  :doc "My custom window map"
  "D" #'delete-other-frames
  "b" #'display-buffer
  "f" #'make-frame
  "k" #'kill-buffer-and-window
  "o" #'other-frame
  "m" #'nc/window-menu
  "M-n" #'windmove-display-new-frame
  "C-d" #'windmove-delete-down
  "C-u" #'windmove-delete-up
  "C-l" #'windmove-delete-left
  "C-r" #'windmove-delete-right)

(keymap-set global-map "C-c w" nc-window-map)

(defvar-keymap nc-external-map
  :doc "My custom external map"
  ;; Open Commands
  "c" #'calc
  "o" #'crux-open-with
  "l" #'nc/open-bookmark)

(keymap-set global-map "C-c x" nc-external-map)




;; (defvar-keymap nc-prefix-map
;;   :doc "My global prefix keymap"

  
;;   ":" #'avy-goto-char-timer
  
;;   "c" nc-code-map
;;   "f" nc-file-map
;;   "g" nc-goto-map
;;   "i" nc-insert-map
;;   "k" nc-kill-map
  
;;   "n" nc-notes-map
;;   "o" nc-open-map
;;   "p" #'projectile-command-map
;;   "w" nc-window-map
  
;;   "C-j" #'crux-top-join-line
;;   "C-l" #'nc/open-bookmark
;;   "C-p" #'consult-projectile
;;   "C-s" #'nc/consult-line-symbol-at-point
;;   "C-v" #'nc/vc-browse-remote-current-line

;;   "M-b" #'nc/buffer-menu
;;   "M-f" #'nc/file-menu
;;   "M-g" #'nc/goto-menu
;;   "M-p" #'nc/project-menu
;;   "M-s" #'nc/search-menu
;;   "M-t" #'nc/toggle-menu
;;   "M-w" #'nc/window-menu)


;; (which-key-add-keymap-based-replacements nc-prefix-map
;;   "c" `("Code"  . ,nc-code-map)
;;   "f" `("File"  . ,nc-file-map)
;;   "g" `("Goto"  . ,nc-goto-map)
;;   "i" `("Insert"  . ,nc-insert-map)
;;   "k" `("Kill"  . ,nc-kill-map)
;;   "n" `("Notes"  . ,nc-notes-map)
;;   "o" `("Open"  . ,nc-open-map)
;;   "w" `("Windows"  . ,nc-window-map)
;;   )

;; (keymap-set global-map "C-;" nc-prefix-map)
;; (keymap-set global-map "C-c C-;" nc-prefix-map)

(transient-define-prefix nc/toggle-menu ()
  "Toggle common Emacs settings."
  ["Toggle Menu"
   
   ["Display"
    ("l" "Line Numbers" nc/toggle-line-numbers
     :transient t
     :description (lambda ()
                    (format "Line Numbers %s"
                            (if (bound-and-true-p display-line-numbers-mode)
                                "[ON]" "[OFF]"))))
    ;; ("L" "Linum Mode" linum-mode
    ;;  :transient t
    ;;  :description (lambda ()
    ;;                 (format "Linum Mode %s"
    ;;                         (if (bound-and-true-p linum-mode)
    ;;                             "[ON]" "[OFF]"))))
    ("t" "Truncate Lines" toggle-truncate-lines
     :transient t
     :description (lambda ()
                    (format "Truncate Lines %s"
                            (if truncate-lines "[ON]" "[OFF]"))))
    ("w" "Whitespace Mode" whitespace-mode
     :transient t
     :description (lambda ()
                    (format "Whitespace Mode %s"
                            (if (bound-and-true-p whitespace-mode)
                                "[ON]" "[OFF]"))))
    ("v" "Visual Line Mode" visual-line-mode
     :transient t
     :description (lambda ()
                    (format "Visual Line Mode %s"
                            (if (bound-and-true-p visual-line-mode)
                                "[ON]" "[OFF]"))))
    ("h" "HL Line Mode" hl-line-mode
     :transient t
     :description (lambda ()
                    (format "HL Line Mode %s"
                            (if (bound-and-true-p hl-line-mode)
                                "[ON]" "[OFF]"))))]
   
   ["Editing"
    ("a" "Auto Fill Mode" auto-fill-mode
     :transient t
     :description (lambda ()
                    (format "Auto Fill Mode %s"
                            (if (bound-and-true-p auto-fill-function)
                                "[ON]" "[OFF]"))))
    ("o" "Overwrite Mode" overwrite-mode
     :transient t
     :description (lambda ()
                    (format "Overwrite Mode %s"
                            (if (bound-and-true-p overwrite-mode)
                                "[ON]" "[OFF]"))))
    ("r" "Read Only Mode" read-only-mode
     :transient t
     :description (lambda ()
                    (format "Read Only Mode %s"
                            (if buffer-read-only "[ON]" "[OFF]"))))
    ("s" "Smartparens Mode" smartparens-mode
     :transient t
     :description (lambda ()
                    (format "Smartparens Mode %s"
                            (if (bound-and-true-p smartparens-mode)
                                "[ON]" "[OFF]"))))
    ("S" "Smartparens Strict Mode" smartparens-strict-mode
     :transient t
     :description (lambda ()
                    (format "Smartparens Strict Mode %s"
                            (if (bound-and-true-p smartparens-strict-mode)
                                "[ON]" "[OFF]"))))
    
    ("p" "Show Paren Mode" show-paren-mode
     :transient t
     :description (lambda ()
                    (format "Show Paren Mode %s"
                            (if (bound-and-true-p show-paren-mode)
                                "[ON]" "[OFF]"))))
    
    ("e" "Electric Pair Mode" electric-pair-mode
     :transient t
     :description (lambda ()
                    (format "Electric Pair Mode %s"
                            (if (bound-and-true-p electric-pair-mode)
                                "[ON]" "[OFF]"))))]
   
      
   ["Completion & Help"
    ;; ("c" "Company Mode" company-mode
    ;;  :transient t
    ;;  :description (lambda ()
    ;;                 (format "Company Mode %s"
    ;;                         (if (bound-and-true-p company-mode)
    ;;                             "[ON]" "[OFF]"))))
    ("E" "Eldoc Mode" eldoc-mode
     :transient t
     :description (lambda ()
                    (format "Eldoc Mode %s"
                            (if (bound-and-true-p eldoc-mode)
                                "[ON]" "[OFF]"))))
    ("f" "Flycheck Mode" flycheck-mode
     :transient t
     :description (lambda ()
                    (format "Flycheck Mode %s"
                            (if (bound-and-true-p flycheck-mode)
                                "[ON]" "[OFF]"))))
    ("F" "Flymake Mode" flymake-mode
     :transient t
     :description (lambda ()
                    (format "Flymake Mode %s"
                            (if (bound-and-true-p flymake-mode)
                                "[ON]" "[OFF]"))))]
   
   ["Visual & Colors"
    ("R" "Rainbow Mode" rainbow-mode
     :transient t
     :description (lambda ()
                    (format "Rainbow Mode %s"
                            (if (bound-and-true-p rainbow-mode)
                                "[ON]" "[OFF]"))))
    ;; ("D" "Rainbow Delimiters" rainbow-delimiters-mode
    ;;  :transient t
    ;;  :description (lambda ()
    ;;                 (format "Rainbow Delimiters %s"
    ;;                         (if (bound-and-true-p rainbow-delimiters-mode)
    ;;                             "[ON]" "[OFF]"))))
    ;; ("i" "Indent Guide" highlight-indent-guides-mode 
    ;;  :transient t
    ;;  :description (lambda ()
    ;;                 (format "Indent Guide %s"
    ;;                         (if (bound-and-true-p highlight-indent-guides-mode)
    ;;                             "[ON]" "[OFF]"))))
    ]
   
   ["UI & Sidebar"
    ("m" "Menu Bar" menu-bar-mode
     :transient t
     :description (lambda ()
                    (format "Menu Bar %s"
                            (if (bound-and-true-p menu-bar-mode)
                                "[ON]" "[OFF]"))))
    ("T" "Tool Bar" tool-bar-mode
     :transient t
     :description (lambda ()
                    (format "Tool Bar %s"
                            (if (bound-and-true-p tool-bar-mode)
                                "[ON]" "[OFF]"))))
    ("S" "Scroll Bar" scroll-bar-mode
     :transient t
     :description (lambda ()
                    (format "Scroll Bar %s"
                            (if (bound-and-true-p scroll-bar-mode)
                                "[ON]" "[OFF]"))))
    ("M" "Treemacs" treemacs
     :transient t
     :description (lambda ()
                    (format "Treemacs %s"
                            (if (and (fboundp 'treemacs-current-visibility)
                                     (eq (treemacs-current-visibility) 'visible))
                                "[ON]" "[OFF]"))))]
   
   ["Debug & Dev"
    ("d" "Debug on Error" toggle-debug-on-error
     :transient t
     :description (lambda ()
                    (format "Debug on Error %s"
                            (if debug-on-error "[ON]" "[OFF]"))))
    ("Q" "Debug on Quit" toggle-debug-on-quit
     :transient t
     :description (lambda ()
                    (format "Debug on Quit %s"
                            (if debug-on-quit "[ON]" "[OFF]"))))
    ;; ("g" "Aggressive Indent" aggressive-indent-mode
    ;;  :transient t
    ;;  :description (lambda ()
    ;;                 (format "Aggressive Indent %s"
    ;;                         (if (bound-and-true-p aggressive-indent-mode)
    ;;                             "[ON]" "[OFF]"))))
    ]
   
   ["Actions"
    ("q" "Quit" transient-quit-one)]])

  (defun nc/toggle-line-numbers ()
    "Toggle line numbers."
    (interactive)
    (if (fboundp 'display-line-numbers-mode)
        (display-line-numbers-mode 'toggle)
      (linum-mode 'toggle)))

(provide 'setup-keys)
;;; setup-keys.el ends here
