;;; setup-menus.el --- Transient Menus Module -*- lexical-binding: t; buffer-read-only: t; no-byte-compile: t -*-

;; Author: Nicolas CHAPON
;; Keywords: Emacs configuration
;; Homepage:

;;; Commentary:
;; Emacs config file.
;; This file was automatically generated by `org-babel-tangle'.
;; Do not change this file.  Main config is located in Readme.org at `user-emacs-directory'

;;; Code:

(use-package transient
    :commands (transient-define-prefix))

;; Stolen from Doom
(defun nc/yank-buffer-path ()
  "Copy the file name or directory name of the current buffer to the clipboard."
  (interactive)
  (let* ((filename (or buffer-file-name default-directory))
         (project (ignore-errors (project-root (project-current))))
         (relpath (if (and project (file-in-directory-p filename project))
                      (file-relative-name filename project)
                    nil)))
    (kill-new
     (cond
      ((equal current-prefix-arg '(4)) ; C-u
       (file-name-nondirectory filename))
      ((equal current-prefix-arg '(16)) ; C-u C-u
       (or relpath filename))
      (t
       filename)))
    (message "Copied: %s"
             (substring-no-properties (car kill-ring)))))

(transient-define-prefix nc/yank-path-menu ()
  "Yank Paths"
  
  [["Yank Paths"
   ("F" "Full path"
    (lambda () (interactive)
      (let ((current-prefix-arg nil))
        (call-interactively #'nc/yank-buffer-path))))

   ("f" "Filename only"
    (lambda () (interactive)
      (let ((current-prefix-arg '(4)))
        (call-interactively #'nc/yank-buffer-path))))

   ("p" "Project relative path"
    (lambda () (interactive)
      (let ((current-prefix-arg '(16)))
        (call-interactively #'nc/yank-buffer-path))))
   ]])

(transient-define-prefix nc/file-menu ()
  "File"
  
  [["Actions"
   ("r" "Rename file & buffer" rename-visited-file)
   ("d" "Delete file & buffer" crux-delete-file-and-buffer)
   ("c" "Copy file" crux-copy-file-preserve-attributes)
   ("y" "Yank buffer path..." nc/yank-path-menu)]
  ])

(transient-define-prefix nc/window-menu ()
  "Simple frame, window and buffer management."
  ["Frame, Window & Buffer Manager"
   
   ["Frames"
    ("n" "New frame" make-frame-command)
    ("d" "Delete frame" delete-frame)
    ("o" "Other frame" other-frame)
    ("D" "Only this frame" delete-other-frames)
    ("m" "Maximize" toggle-frame-maximized)
    ("f" "Fullscreen" toggle-frame-fullscreen)]
   
   ["Layouts"
    ("L i" "IDE layout" nc/layout-ide)
    ("L l" "Sidebar left" nc/layout-sidebar-left)
    ("L r" "Sidebar right" nc/layout-sidebar-right)]
   
   ["Buffers"
    ("B" "Buffer other window" switch-to-buffer-other-window)
    ("F" "Buffer other frame" switch-to-buffer-other-frame)
    ("b" "Display buffer" display-buffer)
    ("K" "Kill buffer & window" kill-buffer-and-window)
    ("i" "Ibuffer" ibuffer)]
   
   ["Actions"
    ("s" "Save config" window-configuration-to-register)
    ("r" "Restore config" jump-to-register)
    ("x" "Swap windows" window-swap-states)
    ("q" "Quit" transient-quit-one)]])

(defun nc/goto-ssh-config-file ()
  "Goto my ssh config files"
  (interactive)
  (find-file "~/.ssh/config"))

(defun nc/goto-authinfo-file ()
  "Goto my auth info file"
  (interactive)
  (find-file "~/.authinfo.gpg"))

(transient-define-prefix nc/goto-menu ()
  "Goto Transient Menu"
  
  [["Config File & Credentials"
    ("e" "Emacs Config" nc/goto-emacs-config)
    ("p" "Credentials" nc/goto-my-credentials)
    ("s" "SSH config"  nc/goto-ssh-config-file)
    ("a" "Authinfo"  nc/goto-authinfo-file)
  ]
  ["Dirs"
    ("A" "Archives" nc/goto-archives-dir)
    ("H" "Home" (lambda () (interactive) (dired "~")))
    ("N" "Notes" nc/goto-notes-dir)
    ("T" "Templates" nc/goto-templates-dir)
    ("P" "Projects" nc/goto-projects-dir)
    ]])

(transient-define-prefix nc/search-menu ()
  "Transient Search Menu"
  ["Search"
   ["Org Files"
    ("a" "Agenda Heading" consult-org-agenda)
    ("n" "Notes" nc/search-notes)]
   ["Projects"
    ("p" "Search in Projects" nc/consult-rg-my-projects)
    ("." "symbol" nc/consult-line-symbol-at-point)]])
