;;; setup-programming.el --- Programming configuration module -*- lexical-binding: t; buffer-read-only: t; no-byte-compile: t -*-

;; Author: Nicolas CHAPON
;; Keywords: Emacs configuration
;; Homepage:

;;; Commentary:
;; Emacs config file.
;; This file was automatically generated by `org-babel-tangle'.
;; Do not change this file.  Main config is located in Readme.org at `user-emacs-directory'

;;; Code:

(use-package compile
  :defer t
  :hook ((compilation-filter . ansi-color-compilation-filter))
  :config
  (setopt compilation-scroll-output t)
  (setopt compilation-ask-about-save nil)
  (require 'ansi-color))

(use-package lsp-mode
  :commands lsp
  :bind
  (:map lsp-mode-map
        ( ;;("C-\M-b" . lsp-find-implementation)
         ("M-RET" . lsp-execute-code-action)))
  :bind-keymap ("C-c l m" . lsp-command-map)
  :hook (lsp-mode . lsp-enable-which-key-integration)
  :config
  (setq ; recommended
   gc-cons-threshold (* 100 1024 1024)
   read-process-output-max (* 1024 1024))
  
  (setq ; optional
   ;; lsp-clojure-custom-server-command '("/Users/nchapon/_PIM/tmp/2del/clojure-lsp") 

                                        ; Features
   lsp-lens-enable t
                                        ;lsp-semantic-tokens-enable t

   lsp-headerline-breadcrumb-enable nil ;; disable breadcrumb

   lsp-completion-provider :none

   ;; Conflicts with other Clojure emacs packages
   cljr-add-ns-to-blank-clj-files nil ; disable clj-refactor adding ns to blank files
   cider-eldoc-display-for-symbol-at-point nil ; disable cider eldoc integration
                                        ; lsp-eldoc-enable-hover nil ; disable lsp-mode showing eldoc during symbol at point
                                        ; lsp-enable-indentation nil ; uncomment to use cider indentation instead of lsp
                                        ; lsp-enable-completion-at-point nil ; uncomment to use cider completion instead of lsp

   ;; Terraform
   lsp-disabled-clients '(tfls)

   ))

;; optionally
(use-package lsp-ui
  :defer t
  :hook lsp-mode
  :init
  ;; (setq lsp-ui-doc-alignment 'frame
  ;;       lsp-ui-doc-position  'bottom
  ;;       lsp-ui-doc-use-childframe nil)
  :config

  (setq lsp-ui-imenu-window-fix-width 40)
  ;; WORKAROUND Hide mode-line of the lsp-ui-imenu buffer
  ;; @see https://github.com/emacs-lsp/lsp-ui/issues/243
  (defadvice lsp-ui-imenu (after hide-lsp-ui-imenu-mode-line activate)
    (setq mode-line-format nil))
  :bind (:map lsp-ui-mode-map
              (([remap xref-find-definitions] . lsp-ui-peek-find-definitions)
               ([remap xref-find-references] . lsp-ui-peek-find-references))))

(use-package lsp-treemacs
  :defer t
  :commands lsp-treemacs-errors-list
  :bind (:map lsp-mode-map
              ("C-c ?" . lsp-treemacs-references)
              ("C-c :" . lsp-treemacs-call-hierarchy))
  :config
  
  (setq lsp-treemacs-sync-mode 1))


;; Integration with consult
(use-package consult-lsp
  :defer t)

(with-eval-after-load 'lsp-mode
  ;; Remap `lsp-treemacs-errors-list' (bound to C-c l g e).
  (define-key lsp-mode-map
              [remap lsp-treemacs-errors-list]
              #'consult-lsp-diagnostics)

  ;; Remap `xref-find-apropos' (bound to C-c l g a).
  (define-key lsp-mode-map
              [remap xref-find-apropos]
              #'consult-lsp-symbols))

(defun lsp-save-hooks () "Install save hooks for lsp."
       (add-hook 'before-save-hook #'lsp-format-buffer t t)
       (add-hook 'before-save-hook #'lsp-organize-imports t t))

(defhydra hydra-lsp (:exit t :hint nil)
    "
   Buffer^^               Server^^                   Symbol
  -------------------------------------------------------------------------------------
   [_f_] format           [_M-r_] restart            [_d_] definition   [_i_] implementation  [_o_] documentation
   [_m_] imenu            [_S_]   shutdown           [_D_] declaration  [_t_] type            [_r_] rename
   [_x_] execute action   [_M-s_] describe session   [_R_] references   [_s_] signature"
    ("d" lsp-ui-peek-find-definitions)
    ("D" lsp-find-declaration)
    ("R" lsp-ui-peek-find-references)
    ("i" lsp-ui-peek-find-implementation)
    ("t" lsp-find-type-definition)
    ("s" lsp-signature-help)
    ("o" lsp-describe-thing-at-point)
    ("r" lsp-rename)

    ("f" lsp-format-buffer)
    ("m" lsp-ui-imenu)
    ("x" lsp-execute-code-action)

    ("M-s" lsp-describe-session)
    ("M-r" lsp-restart-workspace)
    ("S" lsp-shutdown-workspace))
(global-set-key (kbd "C-l") 'hydra-lsp/body)

(use-package flycheck
  :hook ((lsp-mode . flycheck-mode))
  :init
  (setq flycheck-indication-mode 'right-fringe)
  ;; only check on save
  (setq flycheck-check-syntax-automatically '(mode-enabled save)))

;; (use-package dap-mode
;;   ;; Uncomment the config below if you want all UI panes to be hidden by default!
;;   ;; :custom
;;   ;; (lsp-enable-dap-auto-configure nil)
;;   ;; :config
;;   ;; (dap-ui-mode 1)
;;   :commands dap-debug

;;   :config
;;   ;; Enable DAP UI automatically
;;   (dap-ui-mode 1)
;;   (dap-tooltip-mode 1)
;;   (tooltip-mode 1)

;;   ;; Enable DAP controls in the modeline
;;   (dap-ui-controls-mode 1)
  
;;   (require 'dap-hydra)

;;   ;; Bind `C-c l d` to `dap-hydra` for easy access

;;   (dap-register-debug-template "Python :: Attach to running process"
;;   (list :type "python"
;;         :request "attach"
;;         :processId "${command:pickProcess}"
;;         :name "Python :: Attach to running process")))

(use-package with-venv)

(use-package dap-mode
  :after lsp-mode
  :commands dap-debug
  :config
  (require 'dap-python)
  (setq dap-python-debugger 'debugpy)
  (defun dap-python--pyenv-executable-find (command)
    (with-venv (executable-find "python")))

  (add-hook 'dap-stopped-hook
            (lambda (arg) (call-interactively #'dap-hydra))))

(use-package treesit-auto
  :ensure t
  :custom
  (treesit-auto-install 'prompt)
  :config
  (treesit-auto-add-to-auto-mode-alist 'all)
  (setq treesit-auto-langs '(python yaml json))
  (global-treesit-auto-mode))

(use-package combobulate
    :defer t
    :bind
    ("C-c o o" . combobulate)
    :hook ((python-ts-mode . combobulate-mode)
           (yaml-ts-mode . combobulate-mode)
           (json-ts-mode . combobulate-mode))
    ;; Amend this to the directory where you keep Combobulate's source
    ;; code.
    :load-path ("~/Projects/_playground/combobulate"))

(use-package smartparens
  :defer t
  :diminish ""
  :hook (((clojure-mode
           emacs-lisp-mode
           common-lisp-mode
           scheme-mode
           lisp-mode
           cider-repl-mode
           inferior-lisp-mode
           inferior-emacs-lisp-mode)
          . smartparens-strict-mode)
         (prog-mode . smartparens-mode))

  :bind (:map smartparens-mode-map
              ("C-M-q" . sp-indent-defun)
              :map smartparens-strict-mode-map
              (";" . sp-comment))

  :config
  (require 'smartparens-config)
  (sp-use-paredit-bindings)
  ;; Unbind sp-convolute-xexp (conflict with xref-find-references / lsp-ui-peek-find-references)
  (unbind-key "M-?" smartparens-mode-map)

  (define-key smartparens-mode-map (kbd "M-r") 'sp-rewrap-sexp) ; needs to be set manually, because :bind section runs before config
  (setq smartparens-strict-mode t)
  (sp-local-pair 'emacs-lisp-mode "`" nil :when '(sp-in-string-p))

  (defun nc--create-newline-and-enter-sexp (&rest _ignored)
    "Open a new brace or bracket expression, with relevant newlines and indent. "
    (newline)
    (indent-according-to-mode)
    (forward-line -1)
    (indent-according-to-mode))

  (sp-with-modes '(c-mode c++-mode js-mode js2-mode java-mode
                          typescript-mode perl-mode)
    (sp-local-pair "{" nil :post-handlers
                   '((nc--create-newline-and-enter-sexp "RET")))))

(use-package paren
  :straight nil
  :hook (prog-mode . show-paren-mode)
  :custom
  (show-paren-delay 0)
  (show-paren-when-point-in-periphery t))

(use-package devdocs
  :bind ("C-h D" . devdocs-lookup))

(use-package clojure-mode
  :hook
  ((clojure-mode . lsp)
   (clojurec-mode . lsp)
   (clojurescript-mode . lsp)
   (clojure-mode . lsp-save-hooks))
  :init
  (setq clojure-align-forms-automatically t))

(use-package cider
  :init
  (setq org-babel-clojure-backend 'cider)
  :bind ([remap cider-pprint-eval-last-sexp] . cider-pprint-eval-last-sexp-to-comment))

(use-package dockerfile-mode
  :mode "Dockerfile.*\\'")

(use-package go-mode
  :defer t)

(use-package just-mode
  :defer t)

(use-package lua-mode
  :mode "\\.lua\\'")

(use-package markdown-mode
  :mode (("README\\.md\\'" . gfm-mode)
         ("\\.md\\'"       . markdown-mode)
         ("\\.markdown\\'" . markdown-mode))
  :bind
  (:map markdown-mode-map
        ("C-; C-;" . nc/transient-markdown-menu))
  :config
  (setq markdown-live-preview-delete-export 'delete-on-destroy)
  (setq markdown-fontify-code-blocks-natively t)
  (setq markdown-split-window-direction 'right)
  ;; Process Markdown with Pandoc, using GitHub stylesheet for nice output
  (let ((stylesheet (expand-file-name
                     (locate-user-emacs-file "etc/pandoc.css"))))
    (setq markdown-command
          (concat "pandoc --toc --section-divs"
                  " --css   file://" stylesheet
                  " --standalone -f markdown -t html5"
                     )))
  )

(use-package markdown-toc
  :after markdown-mode)

;; From https://www.jamescherti.com/emacs-markdown-table-of-contents-update-before-save/
;; The following functions and hooks guarantee that any existing table of
;; contents remains current whenever changes are made to the markdown file,
;; while also ensuring that both the window start and cursor position remain
;; unchanged.
(defun nc/markdown-toc-gen-if-present ()
  "Generate a table of contents if it is already present."
  (let ((marker (point-marker))
        (current-visual-line
         (save-excursion
           (beginning-of-visual-line)
           (count-screen-lines (window-start) (point)))))
    (unwind-protect
        (when (markdown-toc--toc-already-present-p)
          (markdown-toc-generate-toc))
      (progn
        (goto-char (marker-position marker))
        (when (> current-visual-line 0)
          (let ((window-start (save-excursion
                                (beginning-of-visual-line)
                                (let ((line-move-visual t)
                                      (line-move-ignore-invisible nil))
                                  (line-move (* -1 current-visual-line)))
                                (beginning-of-visual-line)
                                (point))))
            (set-window-start (selected-window) window-start)))))))

(defun nc/setup-markdown-toc ()
  "Setup the markdown-toc package."
  (add-hook 'before-save-hook #'nc/markdown-toc-gen-if-present nil t))

(add-hook 'markdown-mode-hook #'nc/setup-markdown-toc)
;; (add-hook 'markdown-ts-mode-hook #'my-setup-markdown-toc)
;; (add-hook 'gfm-mode-hook #'my-setup-markdown-toc)


;; Render Markdwon with GitHub API
(use-package gh-md
  :after markdown-mode
  :bind 
  (:map markdown-mode-map
        ([remap markdown-preview] . gh-md-render-buffer)))

(transient-define-prefix nc/transient-markdown-menu ()
  "Markdown Transient Menu"
  [
   ["Actions"
    ("p" "PlantUML preview" nc/plantuml-preview-current-block)]])

(use-package plantuml-mode
  :init
  (setq plantuml-default-exec-mode 'jar)
  (setq plantuml-jar-path (expand-file-name "~/opt/plantuml.jar"))
  (setq org-plantuml-jar-path (expand-file-name "~/opt/plantuml.jar"))
  ;; (setq org-startup-with-inline-images t)
  ;; (add-to-list 'org-src-lang-modes '("plantuml" . plantuml))
  ;; (org-babel-do-load-languages 'org-babel-load-languages '((plantuml . t)))
  :mode "\\.puml\\'"
  :bind
  (:map plantuml-mode-map
        ("C-c C-p" . nc/plantuml-generate-png)
        ("C-; C-;" . nc/transient-plantuml-menu))
  :config
  (setq plantuml-output-type "png")
  (defun nc/plantuml-generate-png ()
    (interactive)
    (when (buffer-modified-p)
      (error "There are unsaved changes!!!"))
    (let* ((input (expand-file-name (buffer-file-name)))
           (output (concat (file-name-sans-extension input) ".png"))
           (output-buffer (get-file-buffer output)))
      (message (format "Rendering %s" input))
      (call-process "java" nil t nil
                    ;; the jar file...
                    "-jar"
                    (expand-file-name plantuml-jar-path)
                    "-charset" "UTF-8"
                    input
                    "-tpng")
      (if output-buffer
          (with-current-buffer output-buffer
            (revert-buffer-quick)
            (pop-to-buffer output-buffer))
        (find-file-other-window output)))))


(defun nc/plantuml-preview-current-block (prefix)
  "PlantUML preview current block (hack windows to byPass the pb preview)"
  (interactive "P")
  (when is-windows
    (let* ((image-buffer-name "plantuml-preview.png")
           (preview-file (concat "~/Documents/" image-buffer-name)))
      (when (file-exists-p preview-file)
        (delete-file preview-file))

      (plantuml-preview-current-block 1)
      (when (buffer-live-p (get-buffer image-buffer-name))
        (set-buffer image-buffer-name)
        (set-buffer-modified-p nil)
        (kill-this-buffer))
      
      (with-current-buffer (get-buffer "*PLANTUML Preview*")
        (write-file preview-file)
        (set-buffer image-buffer-name)
        (save-buffer)
        (image-mode))))
  (when is-mac
    (plantuml-preview-current-block 1))
  (when is-linux
    (plantuml-preview-current-block 1)))

(transient-define-prefix nc/transient-plantuml-menu ()
  "Python tools"
  [
   ["Actions"
    ("p" "Preview" nc/plantuml-preview-current-block)]])

(use-package python
  ;; python-ts-mode is part of Emacs itself, so we use :ensure nil
  :ensure nil
  :mode ("\\.py\\'" . python-ts-mode)
  :defer t
  :init
  ;; Prefer tree-sitter mode over classic python-mode
  (add-to-list 'major-mode-remap-alist
               '(python-mode . python-ts-mode)))

(defun nc/setup-python-environment ()
  "Setup a Python development environment in the current buffer."

  ;; Enable YASnippet mode.
  (yas-minor-mode 1)

  ;; Setup active backends for `python-mode'.
  ;; (company-backend-for-hook 'lsp-completion-mode-hook
  ;;                           '((company-capf :with company-yasnippet)
  ;;                             company-dabbrev-code))

  ;; Enable LSP support in Python buffers.
  (require 'lsp-pyright)
  (lsp-deferred)

  ;; Enable DAP support in Python buffers.
  (require 'dap-python)
  (setq-local dap-python-debugger 'debugpy)

  (dap-mode 1))

;; Configure hooks after `python-ts-mode' is loaded.
(add-hook 'python-ts-mode-hook #'nc/setup-python-environment)

(use-package lsp-pyright
  :defer t
  :init
  ;; Prevent `lsp-pyright' start in multi-root mode.
  ;; This must be set before the package is loaded.
  (setq lsp-pyright-multi-root nil)
  (setq lsp-pyright-typechecking-mode "basic") ;; too much noise in "real" projects
  )

(use-package conda
  :when (executable-find "conda")
  :defer t
  :config
  (conda-env-initialize-interactive-shells)
  (conda-env-initialize-eshell)
  (add-to-list
     'global-mode-string
     '(:eval
       (list
        (if conda-env-current-name
            (propertize (concat "(py: " conda-env-current-name ") ")
                        'face 'font-lock-builtin-face
                        'help-echo "Conda environment"
                        'mouse-face '(:box 1)
                        'local-map (make-mode-line-mouse-map
                                    'mouse-1
                                    (lambda () (interactive)
                                      (conda-env-activate))))
          "")))))

(use-package virtualenvwrapper
  :ensure t
  :defer t
  :init
  (venv-initialize-eshell))

(use-package pyvenv
  :defer t
  :config
  (pyvenv-mode))

(defun nc/format-buffer-with-ruff ()
  "Format the Python buffer using `ruff`."
  (interactive)
  (save-buffer)
  (shell-command (concat "ruff check " (buffer-file-name) " --fix"))
  (shell-command (concat "ruff format " (buffer-file-name)))
  (revert-buffer t t t))

(use-package python-pytest
  :straight '(python-pytest :host github :repo "nchapon/emacs-python-pytest")
  :config
  (setq python-pytest-executable "python -m pytest")
  :bind
  (:map python-ts-mode-map
          ("C-c C-t x" . python-pytest)
          ("C-c C-t t" . python-pytest-function-dwim)
          ("C-c C-t T" . python-pytest-function)
          ("C-c C-t f" . python-pytest-file-dwim)
          ("C-c C-t F" . python-pytest-file)
          ("C-c C-t C-t" . python-pytest-dispatch)
          ("C-c C-t C-r" . python-pytest-repeat)
          ("C-c C-t C-x" . python-pytest-last-failed)))

(use-package python-insert-docstring
  :bind
  (:map python-ts-mode-map
        ("C-c i" . python-insert-docstring-with-google-style-at-point)))

(transient-define-prefix nc/transient-python-menu ()
  "Python tools"
  [
   ["Insert"
    ("d" "DocString" python-insert-docstring-with-google-style-at-point)]
   ["Format"
    ("f" "Ruff Format"  nc/format-buffer-with-ruff)]
   ["Run Tests"
    ("t" "Run tests in current def/class"  python-pytest-function-dwim)
    ("T" "Run tests in current file"  python-pytest-file-dwim)
    ("C-t" "Pytest Submenu..." python-pytest-dispatch)
    ]
   ["Env"
    ("a" "PyVenv Activate" pyvenv-activate)
    ("v" "Show venv"     (lambda ()
                           (interactive)
                           (message "Venv: %s" (getenv "VIRTUAL_ENV"))))]])

(define-key python-ts-mode-map (kbd "C-; C-;") 'nc/transient-python-menu)

(defun my/orderless-python-split (string)
  "Split STRING on spaces and underscores for Python identifiers."
  (split-string string "[ _]+" t))

(defun my/orderless-pyright-filter (cand)
  "Hide private and dunder symbols unless explicitly requested."
  (not (string-match-p "\\`__.*__\\|\\`_[^_]" cand)))

(defun my/orderless-pyright-dispatch (pattern _index _total)
  (cond
   ((string-prefix-p "=" pattern)
    `(orderless-literal . ,(substring pattern 1)))
   ((string-prefix-p "~" pattern)
    `(orderless-initialism . ,(substring pattern 1)))
   ((string-prefix-p "/" pattern)
    `(orderless-regexp . ,(substring pattern 1)))))


(defun my/python-orderless-setup ()
  "Python-only Orderless tuning (Pyright)."
  (setq-local orderless-matching-styles
              '(orderless-literal
                orderless-prefixes
                orderless-initialism
                orderless-flex))

  (setq-local orderless-component-separator
              #'my/orderless-python-split)

  (setq-local orderless-filter
              #'my/orderless-pyright-filter)

  (setq-local orderless-dispatchers
              '(my/orderless-pyright-dispatch)))

(add-hook 'python-ts-mode-hook #'my/python-orderless-setup)



(defun my/python-completion-category ()
  (setq-local completion-category-overrides
              '((file (styles partial-completion))
                (capf (styles orderless)))))

(add-hook 'python-ts-mode-hook #'my/python-completion-category)

(use-package terraform-mode
  :defer t
  :hook ((terraform-mode . lsp)))

(use-package verb
  :defer t
  :config
  (setq verb-auto-kill-response-buffers nil) ; Response buffers killed before sending a request.

  )

(with-eval-after-load 'org
  (define-key org-mode-map (kbd "C-c C-r") verb-command-map))

(use-package web-mode
  :defer t
  :mode (("\\.html\\'" . web-mode)
         ("\\.hbs\\'" . web-mode)
         ("\\.tag$" . web-mode)
         ("\\.ftl$" . web-mode)
         ("\\.jsp$" . web-mode)
         ("\\.vue$" . web-mode)
         ("\\.php$" . web-mode))
  :config
  (add-hook 'web-mode-hook (lambda ()
                             (setq web-mode-markup-indent-offset 4)
                             (setq web-mode-code-indent-offset 4))))

(use-package js2-mode
  :mode "\\.js\\'"
  :init
  (defalias 'javascript-generic-mode 'js2-mode)
  :config
  (js2-imenu-extras-setup)
  (setq-default js-auto-indent-flag nil
                js2-strict-missing-semi-warning nil
                js-indent-level 2)

  ;; Don't override global M-j keybinding (join lines)
  (define-key js2-mode-map (kbd "M-j") nil))

(use-package yaml-ts-mode
  :mode ("\\.yaml\\'" "\\.yml\\'")
  :config
  (add-hook 'yaml-ts-mode-hook #'highlight-indent-guides-mode))

(use-package yaml-pro
  :hook (yaml-ts-mode . yaml-pro-ts-mode)
  :config
  (defun yaml-pro-edit-initialize-buffer-filter-args-advice (args)
    (if-let ((mode (language-detection-detect-mode (buffer-string))))
        (cl-destructuring-bind (parent-buffer buffer initial-text type initialize path) args
          (let ((init-func (lambda ()
                             (funcall mode)
                             (when initialize
                               (call-interactively initialize)))))
            (list parent-buffer buffer initial-text type init-func path)))
      args))
  (advice-add 'yaml-pro-edit-initialize-buffer :filter-args #'yaml-pro-edit-initialize-buffer-filter-args-advice)

  :bind
    (:map yaml-pro-ts-mode-map
          ("C-c j" . yaml-pro-ts-move-subtree-down)
          ("C-c k" . yaml-pro-ts-move-subtree-up)
          ("C-c f" . yaml-pro-format)))

(provide 'setup-programming)
;;; setup-programming.el ends here
